from singer_sdk import typing as th

schema = th.PropertiesList(
    th.Property("id", th.IntegerType),
    th.Property("archived", th.BooleanType),
    th.Property("archived_at", th.DateTimeType),
    th.Property("description", th.StringType),
    th.Property("guid", th.StringType),
    th.Property("name", th.StringType),
    th.Property("parent_id", th.IntegerType),
    th.Property("project_code", th.StringType),
    th.Property("secureurl", th.StringType),
    th.Property("secureurl_expiration", th.DateTimeType),
    th.Property("settings", th.IntegerType),
    th.Property("timeentry_lockout", th.IntegerType),
    th.Property("ends_at", th.StringType),
    th.Property("starts_at", th.StringType),
    th.Property("deleted_at", th.DateTimeType),
    th.Property("created_at", th.DateTimeType),
    th.Property("updated_at", th.DateTimeType),
    th.Property("use_parent_bill_rates", th.BooleanType),
    th.Property("type", th.StringType),
    th.Property("project_state_id", th.IntegerType),
    th.Property("thumbnail", th.StringType),
    th.Property("owner_id", th.IntegerType),
    th.Property("owner_name", th.StringType),
    th.Property("phase_name", th.StringType),
    th.Property("has_pending_updates", th.BooleanType),
    th.Property("client", th.StringType),
    th.Property("project_state", th.StringType),
    th.Property("tags", th.ObjectType(
        th.Property("paging", th.ObjectType(
            th.Property("per_page", th.IntegerType),
            th.Property("page", th.IntegerType),
            th.Property("previous", th.StringType),
            th.Property("self", th.StringType),
            th.Property("next", th.StringType),
        )),
        th.Property("data", th.ArrayType(th.ObjectType(
            th.Property("id", th.IntegerType),
            th.Property("custom_field_name", th.StringType),
            th.Property("custom_field_id", th.IntegerType),
            th.Property("value", th.StringType),
            th.Property("created_at", th.DateTimeType),
            th.Property("updated_at", th.DateTimeType),
        ))),
    )),
    th.Property("custom_field_values", th.ObjectType(
        th.Property("paging", th.ObjectType(
            th.Property("per_page", th.IntegerType),
            th.Property("page", th.IntegerType),
            th.Property("previous", th.StringType),
            th.Property("self", th.StringType),
            th.Property("next", th.StringType),
        )),
        th.Property("data", th.ArrayType(th.ObjectType(
            th.Property("id", th.IntegerType),
            th.Property("custom_field_name", th.StringType),
            th.Property("custom_field_id", th.IntegerType),
            th.Property("value", th.StringType),
            th.Property("created_at", th.DateTimeType),
            th.Property("updated_at", th.DateTimeType),
        ))),
    ))
).to_dict()

# Example:
# {'id': 1234567,
#  'archived': True,
#  'archived_at': '2022-01-01',
#  'description': 'Lorem ipsum dolor sit amet',
#  'guid': 'abcdefg-1234-5678-90ab-cdef12345678',
#  'name': 'Project ABC',
#  'parent_id': 9876543,
#  'project_code': 'ABC123',
#  'secureurl': 'https://example.com',
#  'secureurl_expiration': '2022-12-31',
#  'settings': 1,
#  'timeentry_lockout': 60,
#  'ends_at': '2023-12-31',
#  'starts_at': '2022-01-01',
#  'deleted_at': '2022-06-30',
#  'created_at': '2022-01-01T00:00:00Z',
#  'updated_at': '2022-01-01T00:00:00Z',
#  'use_parent_bill_rates': True,
#  'type': 'Project',
#  'project_state_id': 9876543,
#  'thumbnail': 'https://example.com/thumbnail.jpg',
#  'owner_id': 1234567,
#  'owner_name': 'John Doe',
#  'phase_name': 'Phase 1',
#  'has_pending_updates': True,
#  'client': 'Client ABC',
#  'project_state': 'Active',
#  'tags': {'paging': {'per_page': 10,
#    'page': 1,
#    'previous': '/api/v1/projects/1234567/tags?per_page=10&page=1',
#    'self': '/api/v1/projects/1234567/tags?per_page=10&page=1',
#    'next': '/api/v1/projects/1234567/tags?per_page=10&page=2'},
#   'data': [{'id': 9876543,
#     'custom_field_name': 'Tag 1',
#     'custom_field_id': 1234567,
#     'value': 'Value 1',
#     'created_at': '2022-01-01T00:00:00Z',
#     'updated_at': '2022-01-01T00:00:00Z'},
#    {'id': 9876544,
#     'custom_field_name': 'Tag 2',
#     'custom_field_id': 1234568,
#     'value': 'Value 2',
#     'created_at': '2022-01-01T00:00:00Z',
#     'updated_at': '2022-01-01T00:00:00Z'}]},
#  'custom_field_values': {'paging': {'per_page': 10,
#    'page': 1,
#    'previous': '/api/v1/projects/1234567/custom_field_values?per_page=10&page=1',
#    'self': '/api/v1/projects/1234567/custom_field_values?per_page=10&page=1',
#    'next': '/api/v1/projects/1234567/custom_field_values?per_page=10&page=2'},
#   'data': [{'id': 9876545,
#     'custom_field_name': 'Field 1',
#     'custom_field_id': 1234569,
#     'value': 'Value 1',
#     'created_at': '2022-01-01T00:00:00Z',
#     'updated_at': '2022-01-01T00:00:00Z'},
#    {'id': 9876546,
#     'custom_field_name': 'Field 2',
#     'custom_field_id': 1234570,
#     'value': 'Value 2',
#     'created_at': '2022-01-01T00:00:00Z',
#     'updated_at': '2022-01-01T00:00:00Z'}]}}